### ISSUE TITLE
conditions on DEFENSE not working

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedItems#29]
So I found this bug, that this condition im using is not working on DEFENSE trigger on AdvancedItems, im not sure about AdvancedEnchantments and other advanced plugins but yeah

Aitems version: 1.5.2

Video:
https://streamable.com/9j1rjk

Effects:

This one doesn't work, since it's DEFENSE, but try removing conditions, it'll work.
```
DEFENSE:
    conditions: 
    - '%advanceditems helmet type% = ninja1 : %allow%'
    - '%advanceditems chestplate type% = ninja2 : %allow%'
    - '%advanceditems leggings type% = ninja3 : %allow%'
    - '%advanceditems boots type% = ninja4 : %allow%'
    effects:
      - 'POTION:BLINDNESS:0:60 @Attacker'
```

This works, since it's ATTACK
```
ATTACK:
    conditions: 
    - '%advanceditems helmet type% = ninja1 : %allow%'
    - '%advanceditems chestplate type% = ninja2 : %allow%'
    - '%advanceditems leggings type% = ninja3 : %allow%'
    - '%advanceditems boots type% = ninja4 : %allow%'
    effects:
      - 'POTION:SPEED:4:60 @Attacker'
```
