### ISSUE TITLE
DISABLE_ACTIVATION effect not working

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedItems#30]
Please test DISABLE_ACTIVATION effect, ITS NOT WORKING

```
ATTACK:
    conditions: 
    - '%advanceditems helmet type% = chemist1 : %allow%'
    - '%advanceditems chestplate type% = chemist2 : %allow%'
    - '%advanceditems leggings type% = chemist3 : %allow%'
    - '%advanceditems boots type% = chemist4 : %allow%'
    # Find all effects here: https://wiki.advancedplugins.net/abilities/effects
    effects:
      - 'DISABLE_ACTIVATION:divineblessing:10 @Victim'
```

WORKS FOR ADVANCEDENCHANTMENTS, but not AdvancedItems
PLEASE FIX, THANK YOU!
