### ISSUE TITLE
Restricted World not working

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedItems#34]
```
# Example Item
item:
  type: LEATHER_HELMET
  amount: 1
  # You can generate random names for items
  # Read more about it here in wiki:
  name: '&4&lMenace Helmet'
  lore:
  - ''
  - '&f(Requires full menace armor for effects & abilities to work)'
  - ''
  - '&7&oYou are the menace.'
  enchantments:
  - 'protection:4'

settings:
  # Should items be stackable
  disabledStacking: false
  # Should item be used by owner only
  # Owner is the person which receives item when given with commands
  ownerOnly: false
  # Usage limit
  # Set to -1 to disable
  usageLimit: -1
  # Worlds in which this item cannot be used
  restrictedWorlds:
    - 'citadel'
  # Should interactions be disabled? E.g. placing
  disableInteractions: false
  # Should inventory interactions with this item be disabled?
  # If set to true, player won't be able to move this item in inventory
  disableInventoryInteractions: false

# Give this item to player when they join
joinSettings:
  # Should player get this item when they join?
  giveItem: false
  # Should the item given with first join only?
  giveOnlyFirstJoin: false
  # Inventory slot in which item should be
  giveItemSlot: 0

# Abilities are effects that can be used with triggers.
# Read more about abilities here: https://wiki.advancedplugins.net/abilities
abilities:
# Triggers are what activate effects
# Find all triggers here: https://wiki.advancedplugins.net/abilities/triggers
# In this case, when a player or mob attacks another entity, it will activate the effects in this trigger
  EFFECT_STATIC:
    conditions: 
    - '%advanceditems helmet type% = menace1 : %allow%'
    - '%advanceditems chestplate type% = menace2 : %allow%'
    - '%advanceditems leggings type% = menace3 : %allow%'
    - '%advanceditems boots type% = menace4 : %allow%'
    # Find all effects here: https://wiki.advancedplugins.net/abilities/effects
    effects:
      - 'MESSAGE:&7Menace Armor Set&7 has been <if starts>&aEquipped</if starts><if ends>&cUnequipped</if ends>'
      - 'POTION_OVERRIDE:STRENGTH:1'
      - 'POTION_OVERRIDE:SPEED:4'
      - 'POTION_OVERRIDE:RESISTANCE:0'
      - 'POTION_OVERRIDE:REGENERATION:0'
```
The Static effects still are working even if im in world citadel, is it because I'm Opped or what?
