### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedItems#42]
https://mcpaste.io/de6eb3bcaf3f13e9

```
# Example Item
item:
  type: LEATHER_HELMET
  amount: 1
  # You can generate random names for items
  # Read more about it here in wiki:
  name: '&7&lBarbarian Helmet'
  lore:
  - ''
  - '&6&lARMORSET EFFECTS:'
  - '&f• +10% Damage Increase'
  - ''
  - '&6&lARMORSET ABILITY:'
  - '&f• Barbaric - High chance to deal critical strikes'
  - '&f• Barbaric Warcry - When low on HP, you deal more damage and critical strikes chance increases'
  - '&f(Requires full barbarian armor for effects & abilities to work)'
  - ''
  - '&7&oWear this armor and show your enemies the strength of a barbarian.'
  enchantments:
  - 'protection:4'

settings:
  # Should items be stackable
  disabledStacking: false
  # Should item be used by owner only
  # Owner is the person which receives item when given with commands
  ownerOnly: false
  # Usage limit
  # Set to -1 to disable
  usageLimit: -1
  # Worlds in which this item cannot be used
  restrictedWorlds:
    - 'citadel'
  # Should interactions be disabled? E.g. placing
  disableInteractions: false
  # Should inventory interactions with this item be disabled?
  # If set to true, player won't be able to move this item in inventory
  disableInventoryInteractions: false

# Give this item to player when they join
joinSettings:
  # Should player get this item when they join?
  giveItem: false
  # Should the item given with first join only?
  giveOnlyFirstJoin: false
  # Inventory slot in which item should be
  giveItemSlot: 0

# Abilities are effects that can be used with triggers.
# Read more about abilities here: https://wiki.advancedplugins.net/abilities
abilities:
# Triggers are what activate effects
# Find all triggers here: https://wiki.advancedplugins.net/abilities/triggers
# In this case, when a player or mob attacks another entity, it will activate the effects in this trigger
  EFFECT_STATIC:
    conditions: 
    - '%advanceditems helmet type% = barb1 : %allow%'
    - '%advanceditems chestplate type% = barb2 : %allow%'
    - '%advanceditems leggings type% = barb3 : %allow%'
    - '%advanceditems boots type% = barb4 : %allow%'
    # Find all effects here: https://wiki.advancedplugins.net/abilities/effects
    effects:
      - 'MESSAGE:&7Barbarian Armor Set&7 has been <if starts>&aEquipped</if starts><if ends>&cUnequipped</if ends>'
      - 'POTION:SPEED:3'
  ATTACK:
    conditions: 
    - '%advanceditems helmet type% = barb1 : %allow%'
    - '%advanceditems chestplate type% = barb2 : %allow%'
    - '%advanceditems leggings type% = barb3 : %allow%'
    - '%advanceditems boots type% = barb4 : %allow%'
    # Find all effects here: https://wiki.advancedplugins.net/abilities/effects
    effects:
      - 'INCREASE_DAMAGE:10 @Victim'
  DEFENSE:
    conditions: 
    - '%victim advanceditems helmet type% = barb1 : %allow%'
    - '%victim advanceditems chestplate type% = barb2 : %allow%'
    - '%victim advanceditems leggings type% = barb3 : %allow%'
    - '%victim advanceditems boots type% = barb4 : %allow%'
    # Find all effects here: https://wiki.advancedplugins.net/abilities/effects
    effects:
      - 'DECREASE_DAMAGE:10 @Attacker'
```
