### ISSUE TITLE
CONDITION BUG

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedItems#72]
It seems like when my set is incomplete and i try to use the effect, it spams out an error every time it tries the effect, but if your set is complete, it doesnt give out error.

here's my code:
```
abilities:
# Triggers are what activate effects
# Find all triggers here: https://wiki.advancedplugins.net/abilities/triggers
# In this case, when a player or mob attacks another entity, it will activate the effects in this trigger
  ATTACK:
    conditions: 
    - '%advanceditems helmet type% = paladin1 : %allow%'
    - '%advanceditems chestplate type% = paladin2 : %allow%'
    - '%advanceditems leggings type% = paladin3 : %allow%'
    - '%advanceditems boots type% = paladin4 : %allow%'
    # Find all effects here: https://wiki.advancedplugins.net/abilities/effects
    effects:
      - 'INCREASE_DAMAGE:10 @Victim'
  DEFENSE:
    conditions: 
    - '%victim advanceditems helmet type% = paladin1 : %allow%'
    - '%victim advanceditems chestplate type% = paladin2 : %allow%'
    - '%victim advanceditems leggings type% = paladin3 : %allow%'
    - '%victim advanceditems boots type% = paladin4 : %allow%'
    - '%attacker is holding% contains SWORD : %allow%'
    # Find all effects here: https://wiki.advancedplugins.net/abilities/effects
    effects:
      - 'DECREASE_DAMAGE:10 @Attacker'
  REPEATING:
    conditions: 
    - '%advanceditems helmet type% = paladin1 : %allow%'
    - '%advanceditems chestplate type% = paladin2 : %allow%'
    - '%advanceditems leggings type% = paladin3 : %allow%'
    - '%advanceditems boots type% = paladin4 : %allow%'
    # Find all effects here: https://wiki.advancedplugins.net/abilities/effects
    time: 1
    effects:
      - 'POTION_OVERRIDE:HEALTH_BOOST:4:40'
```
and here's the whole log:
https://mcpaste.io/f0322ab790e33d84

CLIP:
https://streamable.com/a1d2y9
